[package]
version = "0.1.0"
name = "speedlaber"
#repository = ""
authors = ["jleahred@gmail.com"]
description = "Laberinth with different speed cells"
categories = ["kata"]
license = "GPL"
readme = "./README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.18"

[dependencies]
seed = "0.8.0"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
