= Scheduler

Sistema para ordenar temporalmente acciones a realizar agrupadas en tareas.

El sistema tendrá una retroalimentación para confirmar que las acciones finalizan con éxito y el momento en el que terminan.

Deberá de replanificarse en caso de fallo o retraso de una acción (incluso de acciones terminadas antes de lo previsto ¿? Aunque eso indicaría un error en la defición de acciones)

Aquí no se exponen cuestiones (al menos de momento) del `executor` a pesar de que debe haber una interacción entre ambos (pero esta debe ser desacoplada)

El modelo no sólo definirá el estado inicial, sino que debe poderse realizar una planificación sobre un estado parcialmente ejecutado


== Elementos

[horizontal]
Task::
    - Se planificará la ejecución completa de la tarea. +
    De no ser posible, o no encontrarse ningún `plan` que lo cumpla, se informará del error
    - Prioridades: `(mandatory, high, low)`
    - Están compuestas de un conjunto de procesos
    - Las tareas son independientes entre sí
    - Indicarán hora a partir de la que se puede iniciar, y hora máxima para que se completen

Products::
    - Habrá `productos` disponibles desde el orignen, y `productos` generados por los procesos
    - Cada producto indicará el tiempo máximo de espera

Process::
    - Tomará unos productos origen, y realizado una acción generará el resultado
    - Se pueden definir varias acciones, y el sistema debe elegir según disponibilidad y la que optimice según la función de evaluación
    - Elementos indivisibles a ejecutar
    - El `proceso` no podrá iniciarse hasta que estén disponibles todos los `inputs` (que pueden existir desde el origen, o pueden ser generados por otra tarea)
    - Siempre que las dependencias y los recursos lo permitan, se pueden ejecutar en paralelo

Actions::
    - En las acciones se pueden programar alarmas pasado x tiempo, o que se repitan cada intervalo de tiempo definido
    - Se requiere una confirmación de cada acción para darla por terminada
    - Algunas acciones pueden ser `cancelables` ¿?

Resources::
    - Para ejecutar una acción, se capturará uno o varios recursos +
      Puede ser un fogón, un horno... _(¿cocinero?)_
    - Se indicará la disponibilidad temporal del recurso +
      Esto puede servir para modelar situaciones en la que el recurso no está disponbile en todo el horario, o para forzar la ejecució de las tareas relacionadas con un recurso en determinados momentos
    - Las acciones son específicas por cada tarea. Los recursos no, son comunes para todas las acciones (y por tanto, tareas)

== Modelo

Task::
    - id
    - description
    - start_after  (time)
    - ends_before  (time)
    - priority   (mandatory, high, medium, low)
    - Process[]

Product::
    - id
    - description
    - quantity
    - max_waitting_time

Process::
    - id
    - description
    - inputs[]
    - -> outputs[]
    - actions[]

Action::
    - id
    - description
    - resources[]
    - min_time  (estimated min time)
    - max_time  (estimated max time)
    - alarms
    - cancellable?

Resources::
    - id
    - description
    - availability[]    (list of periods where the resource is available)

== Función de valoración de planificación

    - Una planificación es válida si es capaz de ejecutar todas las tareas obligatorias en los tiempos indicados

    - Mejor valoración si ejecuta más tareas y de mayor prioridad (la prioridad tiene más peso que el número de tareas)

    - Se podría valorar la "dispersión" temporal de recursos como algo positivo (reducir la utilización simultánea de recursos del mismo tipo)

== INPUT

    - Definición del modelo (tareas, acciones y recursos) +
      Este modelo puede estar parcialmente ejecutado
    - Hora sobre la que realizar la planificación
      En replanificaciones, se indicará la hora actual

== OUTPUT

    - Secuencia de acciones a realizar con hora de inicio de ejecución




== Deploy

- Run `cargo make verify` in your terminal to format and lint the code.
- Run `cargo make build_release`.
- Upload `index.html` and `pkg` into your server's public folder.
   - Don't forget to upload also configuration files for your hosting, see the [Netlify](https://www.netlify.com/) one below.

```toml
# netlify.toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

