= Scheduler

Sistema para ordenar temporalmente acciones a realizar agrupadas en tareas.

El sistema tendrá una retroalimentación para confirmar que las acciones finalizan con éxito y el momento en el que terminan.

Deberá de replanificarse en caso de fallo o retraso de una acción (incluso de acciones terminadas antes de lo previsto ¿? Aunque eso indicaría un error en la defición de acciones)

Aquí no se exponen cuestiones (al menos de momento) del `executor` a pesar de que debe haber una interacción entre ambos (pero esta debe ser desacoplada)

El modelo no sólo definirá el estado inicial, sino que debe poderse realizar una planificación sobre un estado parcialmente ejecutado


== Elementos

[horizontal]
Receta::
    - Conjunto de procesos para conseguir un producto objetivo
    - Se deben ejecutar todos o ninguno

Procesos::
    - Elementos de una receta que indican qué acciones se deben hacer y sus dependencias
    - Se indicará el tiempo estimado de ejecución
    - Generará productos
    - Las dependencias para ejecutar un proceso serán los productos necesisarios, recursos y cocineros

Products::
    - Un proceso se podrá realizar cuando tenga disponibles los productos (entre otras cosas)
    - Además un proceso producirá también productos, lo que generará dependencia entre los procesos
    - Tienen una "caducidad". El producto debe ser utilizado antes de su "vencimiento"

Base de datos de recetas::
    - Tendremos una base de datos con cientos, miles (o más...) o recetas preconfiguradas

Configuración "del día"::
    - Se indicarán las recetas a realizar, señalando su prioridad `Mandatory`, `High`, `Medium`, `Low`
    - Para cada receta se indicará también la hora en la que queremos que esté disponible

== Ejemplo de modelo

=== Base de datos de recetas

```yaml
# -------------- database documents for recipes  ------------------
recipes_db:
  recipe1:
    description: recipe1
    processes:
          proc1:
            description: proc1
            inputs:
              - product1
              - product2
            outputs:
              - prod_id: prod3
                valid_for: 15m
              - prod_id: prod4
                valid_for: 15m
            sequence:
              - do first1
              - do second1
            required_time: 10m
  recipe2:
    description: recipe1
    processes:
          proc2:
            description: proc2
            inputs:
              - product1
              - product2
            # pending  resources and chefs
            outputs:
              - prod_id: prod5
                valid_for: 15m
              - prod_id: prod6
                valid_for: 10m
            sequence:
              - do first2
              - do second2
            required_time: 5m
```

=== Configuraciónd el día

```yaml
# ----------  initial configuration   ---------
recipes_todo:
    - recipe_id: recipe1
      priority: Low
      # pending ends_before
    - recipe_id: recipe2
      priority: High
available_products:
    - product: 
        prod_id: product1
        valid_for: 15m
      available_at: 7m
    - product: 
        prod_id: product2
        valid_for: 15m
      available_at: 7m
```

=== Salida del planificador

```yaml
result:
---
Detail:
  mark: -1
  completed_recipes:
    - recipe2
  executions:
    - start_at: 7m
      duration: 5m
      recipe_id: recipe2
      process_id: proc2
      process_desc: proc2
      sequence:
        - do first2
        - do second2
```

== Deploy

- Run `cargo make verify` in your terminal to format and lint the code.
- Run `cargo make build_release`.
- Upload `index.html` and `pkg` into your server's public folder.
   - Don't forget to upload also configuration files for your hosting, see the [Netlify](https://www.netlify.com/) one below.

```toml
# netlify.toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

