[package]
name = "async"
version = "0.1.0"
authors = ["jleahred <jleahred@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
async-std = "1.2.0"